// Code generated by goctl. DO NOT EDIT.
// Source: RPCDemo.proto

package server

import (
	"context"

	"go-zero-demo/RPCDemo/internal/logic"
	"go-zero-demo/RPCDemo/internal/svc"
	"go-zero-demo/RPCDemo/rPCDemo"
)

type RPCDemoServer struct {
	svcCtx *svc.ServiceContext
	rPCDemo.UnimplementedRPCDemoServer
}

func NewRPCDemoServer(svcCtx *svc.ServiceContext) *RPCDemoServer {
	return &RPCDemoServer{
		svcCtx: svcCtx,
	}
}

func (s *RPCDemoServer) Ping(ctx context.Context, in *rPCDemo.Request) (*rPCDemo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
