// Code generated by goctl. DO NOT EDIT.
package types

type PostDemoReq struct {
	Message string `json:"message"`
}

type PostDemoResp struct {
	Message string `json:"message"`
}

type Request struct {
	Name string `path:"name"`
}

type Response struct {
	Message string `json:"message"`
}
