// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserInfoResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int64  `json:"age"`
}

type UserUpdateReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int64  `json:"age"`
}

type UserUpdateRsp struct {
	Flag bool `json:"flag"`
}
